#This is the deployment file for docker-maven application
apiVersion: apps/v1
kind: Deployment
matadata:
  name: maven-web-k8s-deployment
spec: 
 selector:
  matchLabels:
    app: maven-web-k8s
 replicas: 2 #number of replicas that will be deployed
 template:
   metadata:
     labels:
       app: maven-web-k8s
   specs:
     containers:
       - name: maven-web-k8s
         image: myapp
         ports:
           - containerPort: 8085



---

apiVersion: v1
kind: Service
metadata:
 name: maven-web-k8s
spec: 
  selector: 
    app: maven-web-k8s
  ports:
   - protocol: "TCP"
     port: 8085
     targetPort: 8085
  type: NodePort

